### ISSUE TITLE
Upgrade to v6?

### ISSUE THREAD

**Issue by Gredin67** [YunoHost-Apps/fab-manager_ynh#87]
This is just to say I would be interested if someone could upgrade the package to v6.
@ericgaspar @yalh76 any plan to work on this further ?
Thanks for the work up to now !

**Comment by Gredin67** [comment]
FYI the Working Group for IT tools of the French FabLab Federation is aware of YunoHost and of this package. And their Adminsys is a YunoHost user.
I think they could advertise self-hosting for small FabLabs.

**Comment by Salamandar** [comment]
Done o/
